default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: uncut-ruby-blog-db
  username: postgres

test:
  <<: *default
  database: uncut-ruby-blog-db_test
  username: postgres

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
